### ISSUE TITLE
Vecmathlib compile fails on ARM, LLVM 3.9

### ISSUE THREAD

**Issue by kraiskil** [pocl/pocl#410]
Build of ARM fails with LLVM 3.9 with:
```
/home/buildbot/pocl/pocl/lib/kernel/vecmathlib-pocl/../vecmathlib/vec_neon_float2.h:422:12: error: use of undeclared identifier
      'vfma_f32'; did you mean 'vmla_f32'?
    return vfma_f32(z.v, v, y.v);
```
passing `-mfpu=vfp4` to `DEFAULT_HOST_CLANG_FLAGS` this.
Note: passing `-mfpu=neon` does not fix it.

**Comment by franz** [comment]
FYI, for passing extra arguments to host clang, there's a variable surprisingly called... EXTRA_HOST_CLANG_FLAGS. The DEFAULT_HOST_{CLANG,LLC,AS}_FLAGS vars are setup by pocl internally, and messing with them is not recommended ;)

**Comment by kraiskil** [comment]
Seems clang has started to require a FPU implmentation definition, so I think pocl should set one, per DEFAULT_, internally.  vfpu4 seems like a safe lowest common denominator on cortex-a, I think?
Only, a smarter detect than what is suggested above on what is available and when to disable vecmathlib is certainly need.

**Comment by pjaaskel** [comment]
Does this work with pocl master and LLVM 5.0?

**Comment by franz** [comment]
LLVM 4 and 5 fail to detect the CPU type on both my ARM32 and ARM64 boards, and i have to use `-DLLC_HOST_CPU=<type>` ; with the LLC_HOST_CPU set, pocl/VML compiles.

Anyway, IMO it's not pocl's job to determine what the host CPU does or doesn't support, this needs to be fixed in LLVM. @pjaaskel ideas ?

**Comment by pjaaskel** [comment]
Please retry and reopen if you can still reproduce this with the latest master revision and/or the latest LLVM.
