### ISSUE TITLE
Undefined reference to OpenCL 1.2/2.0 functions 

### ISSUE THREAD

**Issue by jszuppe** [pocl/pocl#301]
I'm trying to build POCL (on my PC and on Travis CI for Boost.Compute), but I've run into a problem. I keep getting `undefined reference to 'cl<function_name>'` whenever I use OpenCL 1.2 or 2.0 function  (for example `undefined reference to 'clEnqueueSVMMemcpy'`). 

It looks like POCL `libOpenCL.so` is built without OpenCL 2.0 and 1.2 functions, but I don't know why. I build POCL from master branch. I use direct linkage, no ICD. OpenCL 1.1 works. I use cmake to build POCL. I get the same errors when building Boost.Compute and simple OpenCL 2.0 program with SVM memory allocation (so it's not Boost.Compute issue). 

I checked OpenCL headers POCL is built against and they are OpenCL 2.0 headers. 

Also see https://github.com/boostorg/compute/issues/493#issuecomment-183737453.

**Comment by kraiskil** [comment]
I tried to repeat the build. 
I can see OCL2.0 functions missing from libpocl.so (e.g. just ```clEnqueueSVMMemcpy````).
But 1.2 functions seem to be there e.g. ```clCreateImage```. We even test for this in the test suite. Does 'make check' pass for your build?

**Comment by haahh** [comment]
I think it's `clLinkProgram` that fails first in Boost.Compute test suite when I use OpenCL 1.2 headers. I've just started a build with 1.2 headers on Travis CI: https://travis-ci.org/haahh/compute/builds/111292382. I'll double check that on my PC later today. I'll also run `make check`, but if I recall correctly it passes with an exception for this https://github.com/pocl/pocl/issues/238.

**Comment by haahh** [comment]
Like I said, only `test_rotate` fails on my PC and it's related to https://github.com/pocl/pocl/issues/238 (Intel Skylake i5 6600K; for POCL it's "broadwell") . 

As for OpenCL 1.2 headers, both on Travis CI (https://travis-ci.org/haahh/compute/builds/111292382#L3888) and on my PC Boost.Compute test suite fails due to ``undefined reference to `clCompileProgram'`` and ``undefined reference to `clLinkProgram'`` errors.

**Comment by kraiskil** [comment]
```clCompileProgram``` and ```clLinkProgram``` don't have implementations in pocl yet. (patches welcome). 
```clEnqueueSVMMemcpy``` does.  When looking more closely at my built libpocl.so, I notice:
```
$ objdump -t lib/CL/libpocl.so | grep clEnqueueSVMMemcpy
0000000000000000 l    df *ABS*	0000000000000000              clEnqueueSVMMemcpy.c
00000000007541e0 l     F .text	0000000000000bd7              POclEnqueueSVMMemcpy
```
I.e. with direct linkage, the internal function name is not exported as a standard-named OCL symbol. A few of the ```cl*SVM*``` implementations lack the ```POsym()``` boilerplate.

**Comment by haahh** [comment]
> clCompileProgram and clLinkProgram don't have implementations in pocl yet. (patches welcome). 

Thanks, I didn't know. I couldn't find any information that it's unimplemented.

**Comment by pjaaskel** [comment]
Was this fixed with @kraiskil's commit?

**Comment by haahh** [comment]
I can link to `cl*SVM*` functions :+1:, but there is still an inconsistency - some unimplemented functions are just `NULL`s in [clGetPlatformIDs.c](https://github.com/pocl/pocl/blob/master/lib/CL/clGetPlatformIDs.c) causing `undefined reference` errors in direct linkage and other unimplemented functions use  `POCL_ABORT_UNIMPLEMENTED()` ([`clSetMemObjectDestructorCallback.c`](https://github.com/pocl/pocl/blob/master/lib/CL/clSetMemObjectDestructorCallback.c) and [more](https://github.com/pocl/pocl/search?p=1&q=POCL_ABORT_UNIMPLEMENTED&utf8=%E2%9C%93)).

**Comment by franz** [comment]
@jszuppe all 1.2 API calls are now implemented in git master, and pocl reports 1.2 as OpenCL version (2.0  is still available but only for HSA enabled builds), so i think this is about as fixed as it can be. Can you retest ?

**Comment by jszuppe** [comment]
Thanks for the info. Is it done in latest release or in `master` branch?

**Comment by jszuppe** [comment]
It looks like OpenCL 1.2 features work, at least all of those tested in Boost.Compute's test suite (not sure if we miss anything). Unfortunately, there are some odd cache errors: https://travis-ci.org/jszuppe/compute/jobs/307286165#L3527.

**Comment by franz** [comment]
Surprisingly, the error happens exactly why pocl claims it happens:

> pocl error: lt_dlopen(".../0-0-0/generate_state.so") failed with 'file not found'.
> note: missing symbols in the kernel binary might be reported as 'file not found' errors

.. somehow local id variables managed to sneak into the .so (again).

**Comment by pjaaskel** [comment]
@franz told this works with LLVM 5.0 plus it's unclear if it's a regression, so not blocking the next release with this.

**Comment by jszuppe** [comment]
Thanks. I'll try with LLVM 5.0 this week.

**Comment by franz** [comment]
@jszuppe did you have time to try it ?

**Comment by pjaaskel** [comment]
Please retry and reopen if you can still reproduce this with the latest master revision and/or the latest LLVM.
