### ISSUE TITLE
pocl 1.0 fails to build on armv7 when CUDA is in use

### ISSUE THREAD

**Issue by flaub** [pocl/pocl#600]
I'm attempting to build against CUDA 6.5 at the moment, since that was the easiest (only?) version of CUDA I can find for ARMv7. I've looked at the compiler error and it appears that one issue might be related to CUDA 6.5, but the other looks like a real build issue for ARM+CUDA. Here's the error:

```
[ 80%] Building C object lib/CL/devices/cuda/CMakeFiles/pocl-devices-cuda.dir/pocl-cuda.c.o
In file included from /home/flaub/src/pocl/pocl-1.0/lib/CL/./pocl_cl.h:47:0,
                 from /home/flaub/src/pocl/pocl-1.0/lib/CL/devices/common.h:28,
                 from /home/flaub/src/pocl/pocl-1.0/lib/CL/devices/cuda/pocl-cuda.c:28:
/home/flaub/src/pocl/pocl-1.0/lib/CL/devices/cuda/pocl-cuda.c: In function ‘pocl_cuda_submit_kernel’:
/home/flaub/src/pocl/pocl-1.0/lib/CL/devices/cuda/pocl-cuda.c:1002:17: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘size_t {aka unsigned int}’ [-Wformat=]
     POCL_ABORT ("[CUDA] Total constant buffer size %u exceeds %lu allocated\n",
                 ^
/home/flaub/src/pocl/pocl-1.0/lib/CL/./pocl_debug.h:97:25: note: in definition of macro ‘POCL_ABORT’
         fprintf(stderr, __VA_ARGS__);                                   \
                         ^
/home/flaub/src/pocl/pocl-1.0/lib/CL/devices/cuda/pocl-cuda.c: In function ‘pocl_cuda_submit_node’:
/home/flaub/src/pocl/pocl-1.0/lib/CL/devices/cuda/pocl-cuda.c:1104:16: warning: implicit declaration of function ‘cuStreamWaitValue32’ [-Wimplicit-function-declaration]
       result = cuStreamWaitValue32 (stream, dev_ext_event_flag, 1,
                ^
/home/flaub/src/pocl/pocl-1.0/lib/CL/devices/cuda/pocl-cuda.c:1105:37: error: ‘CU_STREAM_WAIT_VALUE_GEQ’ undeclared (first use in this function)
                                     CU_STREAM_WAIT_VALUE_GEQ);
                                     ^
/home/flaub/src/pocl/pocl-1.0/lib/CL/devices/cuda/pocl-cuda.c:1105:37: note: each undeclared identifier is reported only once for each function it appears in
/home/flaub/src/pocl/pocl-1.0/lib/CL/devices/cuda/pocl-cuda.c: In function ‘pocl_cuda_finalize_command’:
/home/flaub/src/pocl/pocl-1.0/lib/CL/devices/cuda/pocl-cuda.c:1356:40: error: request for member ‘run’ in something not a structure or union
       cl_kernel kernel = event->command.run.kernel;
                                        ^
/home/flaub/src/pocl/pocl-1.0/lib/CL/devices/cuda/pocl-cuda.c:1357:48: error: request for member ‘run’ in something not a structure or union
       pocl_argument *arguments = event->command.run.arguments;
                                                ^
lib/CL/devices/cuda/CMakeFiles/pocl-devices-cuda.dir/build.make:62: recipe for target 'lib/CL/devices/cuda/CMakeFiles/pocl-devices-cuda.dir/pocl-cuda.c.o' failed
```

In particular, `lib/CL/devices/cuda/pocl-cuda.c:1356` is currently: 
```
cl_kernel kernel = event->command.run.kernel;
pocl_argument *arguments = event->command.run.arguments;
```

But it actually needs to be:
```
cl_kernel kernel = event->command->command.run.kernel;
pocl_argument *arguments = event->command->command.run.arguments;
```

The other build error related to `CU_STREAM_WAIT_VALUE_GEQ` is probably specific to CUDA 6.5.

**Comment by jrprice** [comment]
The proposed change looks good to me - it's been a little while since I tested the CUDA backend on Arm. You are welcome to submit a pull request for that, otherwise I'll try and get to it next week when I have some more time.

I'm not optimistic that the CUDA backend will currently work with anything older than CUDA 8.0. I've never tested with Armv7 (I only have an Armv8+NVIDIA platform), which as you point out doesn't support anything newer than CUDA 6.5.

**Comment by flaub** [comment]
I've just done a bit of reading of the CUDA 6.5 spec, and yeah, there is no `cuStreamWaitValue32` function. It looks like the code is trying to use a word of host memory as the basis for synchronization. I'm trying to piece together what this code is attempting to do. Is this sort of like a condition variable?
Perhaps we can use a pair of `cuEventRecord` (in `pocl_cuda_notify`) and a corresponding `cuEventSynchronize` on the other side (in `pocl_cuda_submit_node`)?

**Comment by jrprice** [comment]
Yes, the use of `cuStreamWaitValue32` is to allow us to enqueue commands into a CUDA stream that are blocked on a flag in host memory. This is how we currently support things like user events, where we want to be able to block a queue/stream until the user application code signals at some arbitrary point.

If this is the only thing stopping the CUDA backend from working at this point, we could potentially just disable this functionality on Armv7, meaning that we wouldn't support user events or mixing GPU+CPU devices on these platforms, which might be a reasonable trade-off. There is at least one much more invasive workaround that would allow us to support this stuff without `cuStreamWaitValue32`, but I'm reluctant to do this at the moment.

**Comment by flaub** [comment]
My application does make use of `clCreateUserEvent`, but perhaps I can also disable this behavior.

Thanks for the info, I can experiment with this and perhaps use `cuStreamWaitEvent` as a way to inject a user event into the stream.

Are there any other major gotchas that you know of off the top of your head that would be related to CUDA 8.0 only functionality?

**Comment by jrprice** [comment]
> Are there any other major gotchas that you know of off the top of your head that would be related to CUDA 8.0 only functionality?

Nothing I can think of right now, but it's been a long time since I tested with anything pre-8.0. There may also be issues with using a 32-bit host CPU - it's not impossible that the codegen or kernel library might assume 64-bit in places.

**Comment by pjaaskel** [comment]
> There may also be issues with using a 32-bit host CPU

There is a known issue:  #597

**Comment by franz** [comment]
#597 has been fixed in git master, pocl should now build again on 32bit ARMs.

**Comment by ayaromenok** [comment]
@pjaaskel - why this bug was closed?
code with errors exist in master branch right now and not allow to compile pocl on armv7/cuda(7.0 - latest for armv7 arch).

**Comment by pjaaskel** [comment]
Ok, misunderstanding.

**Comment by pjaaskel** [comment]
Please retry and reopen if you can still reproduce this with the latest master revision and/or the latest LLVM.
