### ISSUE TITLE
POCL CUDA example1-spir64 fails..

### ISSUE THREAD

**Issue by oscarbg** [pocl/pocl#521]
Hi,
just compiled latest pocl from github using LLVM 4.0 and running tests seems spir64 fails..
if I compile manually spir file using:
llc -march=nvptx64 -mcpu=sm_52 example1.spir -o kernel.ptx
seems generates a valid ptx file but running the sample with:
export POCL_DEBUG=1
export POCL_CUDA_DUMP_NVVM=1
export POCL_DEVICES=CUDA

[2017-08-02 13:24:43.843949265]POCL: in fn compile_and_link_program at line 485:
  |   GENERAL |  building program with options 
[2017-08-02 13:24:43.843954531]POCL: in fn compile_and_link_program at line 553:
  |   GENERAL |  building from a BC binary for device 0
CUDA_ERROR_INVALID_PTX: a PTX JIT compilation failed

using driver 381.26.13 on GTX 970 on Ubuntu 17.04 and "Cuda compilation tools, release 8.0, V8.0.44"

**Comment by jrprice** [comment]
Looks like this was broken in b39a5f0 by @franz. These SPIR binaries are no longer valid because they're linked against pocl's kernel library ahead of time.

As mentioned in the commit message:
> The real fix would be to link the SPIR binaries at clBuildProgram

which I fully agree with. At present I don't think pocl will work with any real SPIR programs if it assumes they are already fully linked.

Not sure I understand the comment about needing a real SPIR kernel library though - why can't we just link against the target specific kernel library?

**Comment by franz** [comment]
> At present I don't think pocl will work with any real SPIR programs

I think it hasn't worked with any real SPIR programs for a while now.

> why can't we just link against the target specific kernel library?

@jrprice because LLVM IR is not architecture / ABI independent. SPIR (which is a particular LLVM IR) has its own datalayout (alignments, vector sizes, integer sizes, pointer size etc). LLVM for good reasons refuses to link two modules with different datalayouts (we currently workaround this by an ugly hack). Each target has its own datalayout, which may or may not be compatible with SPIR. There's also a ton of other problems (builtin types etc) which will likely blow up at link time.

My comment is slightly wrong though, we may not need a SPIR kernel library; we have to translate SPIR to LLVM IR at some point, and we could do it before or after kernel library linking. But we'll need a real SPIR <-> LLVM IR converter for any real SPIR support, the current way pocl does SPIR is just an ugly hack.

**Comment by pjaaskel** [comment]
I believe SPIR support has improved a lot, possibly fixing this, and the focus is now on SPIR-V anyhow.
