### ISSUE TITLE
does not build with clang-3.2-spir

### ISSUE THREAD

**Issue by pjaaskel** [pocl/pocl#63]
The official SPIR producer version of LLVM would be nice to support. It seems not to be compatible with the upstream 3.2 (it probably has more OpenCL C support), thus fails with the type defines:

 llvm-3.2-spir/bin/clang -target x86_64-unknown-linux-gnu -march=penryn -D_CL_DISABLE_LONG -Xclang -ffake-address-space-map -emit-llvm -ffp-contract=off -x cl -D__OPENCL_VERSION__=120 -fsigned-char -c -o abs.cl.bc ../../../lib/kernel/abs.cl -include /home/visit0r/src/pocl/include/_kernel.h
In file included from <built-in>:155:
In file included from <command line>:3:
In file included from /home/visit0r/src/pocl/include/_kernel.h:33:
In file included from /home/visit0r/src/pocl/include/_kernel_c.h:34:
/home/visit0r/src/pocl/include/pocl_types.h:48:9: error: cannot combine with previous 'type-name' declaration specifier
typedef __SIZE_TYPE__ size_t;
        ^
<built-in>:56:37: note: expanded from macro '__SIZE_TYPE__'
#define __SIZE_TYPE__ long unsigned int
                                    ^
In file included from <built-in>:155:
In file included from <command line>:3:
In file included from /home/visit0r/src/pocl/include/_kernel.h:33:
In file included from /home/visit0r/src/pocl/include/_kernel_c.h:34:
/home/visit0r/src/pocl/include/pocl_types.h:48:9: error: 'type-name' cannot be signed or unsigned
typedef __SIZE_TYPE__ size_t;
        ^
<built-in>:56:28: note: expanded from macro '__SIZE_TYPE__'
#define __SIZE_TYPE__ long unsigned int
                           ^
In file included from <built-in>:155:
In file included from <command line>:3:
In file included from /home/visit0r/src/pocl/include/_kernel.h:33:
In file included from /home/visit0r/src/pocl/include/_kernel_c.h:34:
/home/visit0r/src/pocl/include/pocl_types.h:49:9: error: cannot combine with previous 'type-name' declaration specifier
typedef __PTRDIFF_TYPE__ ptrdiff_t;
        ^
<built-in>:52:31: note: expanded from macro '__PTRDIFF_TYPE__'
#define __PTRDIFF_TYPE__ long int
                              ^
In file included from <built-in>:155:
In file included from <command line>:3:
In file included from /home/visit0r/src/pocl/include/_kernel.h:33:
/home/visit0r/src/pocl/include/_kernel_c.h:161:13: error: cannot combine with previous 'int' declaration specifier
typedef int sampler_t;

.... etc ... 

It seems pocl build thinks that the Clang 3.2 does not provide those types (like the upstream doesn't) and try to #define them to something sensible while Clang-SPIR 3.2 does provide. https://github.com/KhronosGroup/SPIR

**Comment by pjaaskel** [comment]
No point to support older Clang versions as newer keep adding supported features.
