### ISSUE TITLE
pthreads Install Trouble on Ubuntu 16.04

### ISSUE THREAD

**Issue by cdeterman** [pocl/pocl#384]
I am trying to install using cmake.  I currently am getting the error in the CMakeError.log

>Determining if the pthread_create exist failed with the following output:
>Change Dir: /home/cdeterman/Downloads/pocl/build/CMakeFiles/CMakeTmp

>Run Build Command:"/usr/bin/make" "cmTC_ae979/fast"
/usr/bin/make -f CMakeFiles/cmTC_ae979.dir/build.make CMakeFiles/cmTC_ae979.dir/build
make[1]: Entering directory '/home/cdeterman/Downloads/pocl/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_ae979.dir/CheckSymbolExists.c.o
/usr/bin/cc    -fPIE   -o CMakeFiles/cmTC_ae979.dir/CheckSymbolExists.c.o   -c /home/cdeterman/Downloads/pocl/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_ae979
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_ae979.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_ae979.dir/CheckSymbolExists.c.o  -o cmTC_ae979 -rdynamic
CMakeFiles/cmTC_ae979.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x1b): undefined reference to `pthread_create'

I have installed pthreads with `sudo apt-get install libpthread-stubs0-dev`

Any thoughts?

**Comment by pjaaskel** [comment]
I cannot reproduce this. Builds on Ubuntu 16.04 just fine. Are you running pocl master?

**Comment by cdeterman** [comment]
@pjaaskel yes I am running pocl master.  I created a Ubuntu 16.04 virtual machine and installed all the components list [here](http://portablecl.org/docs/html/install.html#requirements).  Any thoughts on how to troubleshoot this?  Perhaps your install script if you just tried this on a clean 16.04 machine?

**Comment by pjaaskel** [comment]
I just executed 'mkdir build; cmake ..; make'. Not on a VM though, but I cannot understand why it would make a difference here.

**Comment by cdeterman** [comment]
I deleted the `build` directory and tried again.

```sh
mkdir build
cd build
cmake ..
```

but this resulted in error where I can find again the problem about `pthread_create` in the cmake output

>-- Trying to link LLVM to single big libLLVM
--  .. OK, using /usr/lib/llvm-3.8/lib/libLLVM-3.8.so
-- ltdl found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread._create
-- Looking for pthread._create - not found
-- Looking for pthread._create in pthreads
-- Looking for pthread._create in pthreads - not found
-- Looking for pthread._create in pthread
-- Looking for pthread._create in pthread - found


with the same error in the CMakeError.log file

**Comment by pjaaskel** [comment]
But does that error matter? I think it's normal (I have those too) as it tries to link pthread with different ways and some of them fail (which is OK). Doesn't it build (with 'make') after that?

**Comment by cdeterman** [comment]
No, at the end of the `cmake` output it shows

`-- Configuring incomplete, errors occured!`

You can see the full error file attached
[error_log.txt](https://github.com/pocl/pocl/files/472560/error_log.txt)

**Comment by pjaaskel** [comment]
Please check carefully the cmake's output. The error_log.txt looks fine to me.

**Comment by cdeterman** [comment]
I have no idea then, should I send you the `CMakeOutput.log`?

**Comment by pjaaskel** [comment]
Are you using Ubuntu's LLVM 3.8? Maybe you nede to install libclang-3.8-dev. At least for me, when I tried with the Ubuntu shipped LLVM now, it was missed by cmake.

**Comment by cdeterman** [comment]
Ah! That seems to have done it.  I needed to install libclang-3.8-dev.  The `cmake` and `make` calls worked without problem now.  Thanks.

**Comment by paoletto** [comment]
What version (sha1, tag, etc.) is expected to work on 16.04?

**Comment by franz** [comment]
Versions 1.0 and 1.1 might work (look for `release_X_Y` branches).

**Comment by paoletto** [comment]
@franz thank you, i indeed managed to build and install it (1.2 even), clinfo report is very promising.
However, when i try to build and run julia from https://github.com/bashbaug/SimpleOpenCLSamples i get a segfault.
This works on 18.04 (with a newer pocl iirc). Any idea?
