### PR TITLE
3.1 fixes

### PR DESCRIPTION
**Pull request by franz**
some minor fixes for release 3.1

### CODE REVIEW

**Comment by RABijl** [comment]
@franz I tried running `make prepare_examples`  the following cmake arguments: 
``` 
-G "Unix Makefiles" -DENABLE_TESTSUITES=piglit;PyOpenCL;conformance -DENABLE_CONFORMANCE=ON -DCMAKE_BUILD_TYPE=Release 
```
but I am getting the following errors 
```
In file included from /usr/include/string.h:535,
                 from /home/rabijl/Projects/pocl/cmake-build-release_3_1_test/examples/conformance/src/conformance/test_conformance/compiler/testBase.h:22,
                 from /home/rabijl/Projects/pocl/cmake-build-release_3_1_test/examples/conformance/src/conformance/test_conformance/compiler/test_compiler_defines_for_extensions.cpp:16:
In function ‘char* strcat(char*, const char*)’,
    inlined from ‘int test_compiler_defines_for_extensions(cl_device_id, cl_context, cl_command_queue, int)’ at /home/rabijl/Projects/pocl/cmake-build-release_3_1_test/examples/conformance/src/conformance/test_conformance/compiler/test_compiler_defines_for_extensions.cpp:334:11:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:130:33: error: ‘char* __builtin_strcat(char*, const char*)’ writing 1 or more bytes into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
  130 |   return __builtin___strcat_chk (__dest, __src, __glibc_objsize (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/rabijl/Projects/pocl/cmake-build-release_3_1_test/examples/conformance/src/conformance/test_conformance/compiler/test_compiler_defines_for_extensions.cpp: In function ‘int test_compiler_defines_for_extensions(cl_device_id, cl_context, cl_command_queue, int)’:
/home/rabijl/Projects/pocl/cmake-build-release_3_1_test/examples/conformance/src/conformance/test_conformance/compiler/test_compiler_defines_for_extensions.cpp:330:38: note: destination object of size 0 allocated by ‘malloc’
  330 |     char *kernel_code = (char*)malloc(1025*256*(num_not_supported_extensions+num_of_supported_extensions));
      |                                ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/string.h:535,
                 from /home/rabijl/Projects/pocl/cmake-build-release_3_1_test/examples/conformance/src/conformance/test_conformance/compiler/testBase.h:22,
                 from /home/rabijl/Projects/pocl/cmake-build-release_3_1_test/examples/conformance/src/conformance/test_conformance/compiler/test_compiler_defines_for_extensions.cpp:16:
In function ‘char* strcat(char*, const char*)’,
    inlined from ‘int test_compiler_defines_for_extensions(cl_device_id, cl_context, cl_command_queue, int)’ at /home/rabijl/Projects/pocl/cmake-build-release_3_1_test/examples/conformance/src/conformance/test_conformance/compiler/test_compiler_defines_for_extensions.cpp:334:11:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:130:33: error: ‘char* __builtin_strcpy(char*, const char*)’ writing 1 or more bytes into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
  130 |   return __builtin___strcat_chk (__dest, __src, __glibc_objsize (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/rabijl/Projects/pocl/cmake-build-release_3_1_test/examples/conformance/src/conformance/test_conformance/compiler/test_compiler_defines_for_extensions.cpp: In function ‘int test_compiler_defines_for_extensions(cl_device_id, cl_context, cl_command_queue, int)’:
/home/rabijl/Projects/pocl/cmake-build-release_3_1_test/examples/conformance/src/conformance/test_conformance/compiler/test_compiler_defines_for_extensions.cpp:330:38: note: destination object of size 0 allocated by ‘__builtin_calloc’
  330 |     char *kernel_code = (char*)malloc(1025*256*(num_not_supported_extensions+num_of_supported_extensions));
      |                                ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

@jansol says this has already been fixed upstream.

**Comment by jansol** [comment]
90bfeaa can be dropped since the same change is already in.

Pthread passes all tier1 tests here with these changes plus #1143 applied, so this can be merged as soon as TCE is confirmed working.

**Comment by pjaaskel** [comment]
CUDA fails to build:
```
/home/visit0r/src/pocl/lib/CL/devices/cuda/pocl-cuda.c:235:10: error: ‘CL_DEVICE_ATTRIBUTE_ASYNC_ENGINE_COUNT_NV’ undeclared (first use in this function); did you mean ‘CU_DEVICE_ATTRIBUTE_ASYNC_ENGINE_COUNT’?
/home/visit0r/src/pocl/lib/CL/devices/cuda/pocl-cuda.c:239:10: error: ‘CL_DEVICE_PCI_BUS_ID_NV’ undeclared (first use in this function); did you mean ‘CL_DEVICE_PCI_BUS_INFO_KHR’?
/home/visit0r/src/pocl/lib/CL/devices/cuda/pocl-cuda.c:243:10: error: ‘CL_DEVICE_PCI_SLOT_ID_NV’ undeclared (first use in this function); did you mean ‘CL_DEVICE_PCIE_ID_AMD’?
/home/visit0r/src/pocl/lib/CL/devices/cuda/pocl-cuda.c:247:10: error: ‘CL_DEVICE_PCI_DOMAIN_ID_NV’ undeclared (first use in this function)
```

**Comment by franz** [comment]
@pjaaskel yep that is broken by PR #1143 (now fixed by latest commit), see [my comment](https://github.com/pocl/pocl/pull/1143#issuecomment-1328893426), so unrelated to this PR. Same applies for error in earlier comment from @RABijl.

**Comment by pjaaskel** [comment]
LLVM 9.0 fails at CMake:
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
C_LIBFILE_clangSupport
    linked by target "pocl" in directory /home/visit0r/src/pocl/lib/CL

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by franz** [comment]
Ok, should be fixed now. libclangSupport is a new library in LLVM 15.
