### PR TITLE
Vulkan fixes for testing with multiple devices

### PR DESCRIPTION
**Pull request by RABijl**
plus disables compiler options in vulkan driver

### CODE REVIEW

**Comment by pjaaskel** [comment]
Fails to build:
```
/home/visit0r/src/pocl/lib/CL/devices/vulkan/pocl-vulkan.c: In function ‘pocl_vulkan_init’:
/home/visit0r/src/pocl/lib/CL/devices/vulkan/pocl-vulkan.c:1080:3: error: unknown type name ‘VkPhysicalDeviceShaderAtomicInt64Features’; did you mean ‘VkPhysicalDeviceShaderAtomicInt64FeaturesKHR’?
   VkPhysicalDeviceShaderAtomicInt64Features atomic64b_features
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   VkPhysicalDeviceShaderAtomicInt64FeaturesKHR
/home/visit0r/src/pocl/lib/CL/devices/vulkan/pocl-vulkan.c:1081:11: error: ‘VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_ATOMIC_INT64_FEATURES’ undeclared (first use in this function); did you mean ‘VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_ATOMIC_INT64_FEATURES_KHR’?
       = { VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_ATOMIC_INT64_FEATURES, 0 };
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_ATOMIC_INT64_FEATURES_KHR
/home/visit0r/src/pocl/lib/CL/devices/vulkan/pocl-vulkan.c:1081:11: note: each undeclared identifier is reported only once for each function it appears in
/home/visit0r/src/pocl/lib/CL/devices/vulkan/pocl-vulkan.c:1081:75: warning: excess elements in scalar initializer
       = { VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_ATOMIC_INT64_FEATURES, 0 };
                                                                           ^
...
```

**Comment by jansol** [comment]
Sounds like your vulkan headers might be too old. [VkPhysicalDeviceShaderAtomicInt64Features](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPhysicalDeviceShaderAtomicInt64FeaturesKHR.html) seems to be a Vulkan 1.2 feature.

**Comment by franz** [comment]
This seems like one of my older commits. I have a branch with a few more vulkan fixes, that should also build with vulkan down to 1.1, but i'm not sure if its OK to push into master before release. OTOH vulkan was not in the previous release. @pjaaskel  what do you think ?

**Comment by pjaaskel** [comment]
Please just send a PR and I will pull it to master if it passes my local test envs. We can also pull it to 3.0 since like you said there shouldn't be regressions as it wasn't there before :)
