### ISSUE TITLE
Multiple regressions with PyOpenCL's test suite on master

### ISSUE THREAD

**Issue by inducer** [pocl/pocl#354]
Prompted by #353 (but entirely unrelatedly), I investigated how well current pocl master does on PyOpenCL's test suite. It turns out that 6c51597 (what I tested with) encounters numerous issues.

(All of these want to be run in PyOpenCL's test suite directory)

*   `PYOPENCL_TEST=portable python  test_array.py 'test_basic_complex(cl._csc)'` (miscompiled complex number handling)
*   `PYOPENCL_TEST=portable python  test_algorithm.py 'test_copy_if(cl._csc)'` (crash in generated code)
*   `PYOPENCL_TEST=portable python  test_array.py 'test_pow_neg1_vs_inv(cl._csc)'` (crash with following backtrace)

    ```
    #0  strlen () at ../sysdeps/x86_64/strlen.S:106
    #1  0x00007fffe6e117d4 in pocl_binary_serialize_kernel_to_buffer (buf=0x7fffc3fff051 "", device_i=0, kernel=0x1bcf6e0) at pocl_binary.c:394
    #2  pocl_binary_serialize (program=program@entry=0x12cc830, device_i=device_i@entry=0, size=size@entry=0x7fffffffad28) at pocl_binary.c:572
    #3  0x00007fffe6e11a88 in pocl_binary_sizeof_binary (program=program@entry=0x12cc830, device_i=device_i@entry=0) at pocl_binary.c:630
    #4  0x00007fffe6e0500c in get_binary_sizes (sizes=0x1bfaeb0, program=0x12cc830) at clGetProgramInfo.c:49
    #5  POclGetProgramInfo (program=0x12cc830, param_name=<optimized out>, param_value_size=<optimized out>, param_value=0x1bfaeb0, param_value_size_ret=0x7fffffffae80) at clGetProgramInfo.c:118
    #6  0x00007fffe8d38d9f in _call_func<int (*)(_cl_program*, unsigned int, unsigned long, void*, unsigned long*), 0, 1, 2, 3, 4, _cl_program* const&, int&, unsigned long, unsigned long*, unsigned long*> (args=..., func=<optimized out>) at src/c_wrapper/function.h:38
    #7  call_tuple<int (*&)(_cl_program*, unsigned int, unsigned long, void*, unsigned long*), std::tuple<_cl_program* const&, int&, unsigned long, unsigned long*, unsigned long*> > (args=<optimized out>, func=<synthetic pointer>) at src/c_wrapper/function.h:49
    #8  ArgPack<CLArg, _cl_program* const, int, ArgBuffer<unsigned long, (ArgType)1>, ArgBuffer<unsigned long, (ArgType)0> >::call<__CLArgGetter, int (*)(_cl_program*, unsigned int, unsigned long, void*, unsigned long*)> (func=<optimized out>, this=<synthetic pointer>) at src/c_wrapper/function.h:108
    #9  CLArgPack<_cl_program* const, int, ArgBuffer<unsigned long, (ArgType)1>, ArgBuffer<unsigned long, (ArgType)0> >::clcall<int (*)(_cl_program*, unsigned int, unsigned long, void*, unsigned long*)> (name=0x7fffe8d47791 "clGetProgramInfo", func=<optimized out>, this=<synthetic pointer>) at src/c_wrapper/error.h:210
    #10 call_guarded<_cl_program* const&, int&, ArgBuffer<unsigned long, (ArgType)1>, ArgBuffer<unsigned long, (ArgType)0>, _cl_program*, unsigned int, unsigned long, void*, unsigned long*> (name=0x7fffe8d47791 "clGetProgramInfo", func=<optimized out>) at src/c_wrapper/error.h:242
    #11 get_vec_info<unsigned long, _cl_program*, unsigned int, unsigned long, void*, unsigned long*, _cl_program* const&, int> (name=0x7fffe8d47791 "clGetProgramInfo", func=<optimized out>) at src/c_wrapper/clhelper.h:83
    #12 program::get_info (this=0x1214f40, param=4454) at src/c_wrapper/program.cpp:40
    #13 0x00007fffe8cfad63 in <lambda()>::operator() (__closure=<synthetic pointer>) at src/c_wrapper/wrap_cl.cpp:111
    #14 c_handle_error<clobj__get_info(clobj_t, cl_uint, generic_info*)::<lambda()> > (func=...) at src/c_wrapper/error.h:295
    #15 clobj__get_info (obj=<optimized out>, param=param@entry=4454, out=0x7fffe830eab0) at src/c_wrapper/wrap_cl.cpp:112
    ```

There are many more. These seem "representative". These worked fine with pocl 0.13 as well as with the CL implementations by Nvidia, AMD, Intel, and Apple.

**Comment by inducer** [comment]
Just checked with a62d357d94000fb23a306e1093e0417a9e4d3df1. These are all still present.

**Comment by pjaaskel** [comment]
OK, unfortunately we haven't had the resources to look at this. Could you do a 'git bisect' at least to help fixing this? Thanks.

**Comment by inducer** [comment]
Trying to do that. Having trouble compiling pocl with the following error:
```
/opt/pocl/lib/kernel/vecmathlib-pocl/../vecmathlib/floattypes.h:44:2: error: "isfinite is not a macro"
#error "isfinite is not a macro"
 ^
/opt/pocl/lib/kernel/vecmathlib-pocl/../vecmathlib/floattypes.h:47:2: error: "isinf is not a macro"
#error "isinf is not a macro"
 ^
/opt/pocl/lib/kernel/vecmathlib-pocl/../vecmathlib/floattypes.h:50:2: error: "isnan is not a macro"
#error "isnan is not a macro"
 ^
/opt/pocl/lib/kernel/vecmathlib-pocl/../vecmathlib/floattypes.h:53:2: error: "isnormal is not a macro"
#error "isnormal is not a macro"
 ^
/opt/pocl/lib/kernel/vecmathlib-pocl/../vecmathlib/floattypes.h:56:2: error: "signbit is not a macro"
#error "signbit is not a macro"
```

**Comment by inducer** [comment]
Just commenting out the checks seems to do the trick though.

**Comment by inducer** [comment]
Doing the bisect is being complicated by problems with the build, for instance this:
```
/opt/pocl/lib/CL/clCreateProgramWithBinary.c: In function ‘POclCreateProgramWithBinary’:
/opt/pocl/lib/CL/clCreateProgramWithBinary.c:146:13: error: ‘is_pocl_binary’ undeclared (first use in this function)
       if ( !is_pocl_binary 
             ^
/opt/pocl/lib/CL/clCreateProgramWithBinary.c:146:13: note: each undeclared identifier is reported only once for each function it appears in
/opt/pocl/lib/CL/clCreateProgramWithBinary.c:158:61: error: ‘pocl_binary’ undeclared (first use in this function)
                && pocl_binary_check_binary(device_list[i], (pocl_binary *)binaries[i])) 
                                                             ^
/opt/pocl/lib/CL/clCreateProgramWithBinary.c:158:74: error: expected expression before ‘)’ token
                && pocl_binary_check_binary(device_list[i], (pocl_binary *)binaries[i])) 
                                                                          ^
lib/CL/CMakeFiles/libpocl_unlinked_objs.dir/build.make:614: recipe for target 'lib/CL/CMakeFiles/libpocl_unlinked_objs.dir/clCreateProgramWithBinary.c.o' failed
```
and this:
```
-- Minor llvm version: 8
CMake Error at cmake/LLVM.cmake:155 (message):
  Unknown/unsupported minor llvm version: 8
Call Stack (most recent call first):
  CMakeLists.txt:197 (include)
```

(I'm starting from release_0_13 as the last good build, and master as bad.)

**Comment by inducer** [comment]
Any advice?

**Comment by inducer** [comment]
FWIW, this is how far I got trying to track down the wrong result in

```
PYOPENCL_TEST=portable python test_algorithm.py 'test_dot(cl._csc)' 
```

```
git bisect start
# good: [f68ffcc9ffa48d3463b08b2890f96485a4b49c86] Remove LLVM 3.6 support. It doesn't work anymore.
git bisect good f68ffcc9ffa48d3463b08b2890f96485a4b49c86
# bad: [a62d357d94000fb23a306e1093e0417a9e4d3df1] Hid the hsa_status from the toc tree as it looks weird there.
git bisect bad a62d357d94000fb23a306e1093e0417a9e4d3df1
# bad: [31ce0d33d9a36e683b716f114b7943d7e288397c] Merge branch 'master' into pocl_without_llvm
git bisect bad 31ce0d33d9a36e683b716f114b7943d7e288397c
# bad: [133c35cbaf14bb92c95897d735cfd73661555126] Merge branch 'master' of github.com:pocl/pocl
git bisect bad 133c35cbaf14bb92c95897d735cfd73661555126
# skip: [fbd2f481fe01182992deac41b205bf854fe75986] pocl_binary.c: implement the new binary interface
git bisect skip fbd2f481fe01182992deac41b205bf854fe75986
# skip: [0542ab7db9dfc024d315db1929c71e8f2800c737] clBuildProgram(): build dynamic WG kernel binaries
git bisect skip 0542ab7db9dfc024d315db1929c71e8f2800c737
# skip: [43a2f658ffe762c447b6058d5abf4de0cb52344c] pocl_binary: remove free* functions, add new macros to read binary data
git bisect skip 43a2f658ffe762c447b6058d5abf4de0cb52344c
# bad: [368157cbf8bea5f48371b18ddbab375d53e8e54c] Buildsystem fixes
git bisect bad 368157cbf8bea5f48371b18ddbab375d53e8e54c
```

**Comment by pjaaskel** [comment]
Merges to master should build and work.

**Comment by pjaaskel** [comment]
OK, I took a quick look. Clearly the new poclbin code and/or the TLP rework is the reason. Definitely 0.14 blocker.

**Comment by inducer** [comment]
Thanks! What's the most useful thing I can do to help track this down? Retry the bisect based on only merge points?

**Comment by pjaaskel** [comment]
There were two major merges with a bunch of commits in this cycle. The poclbin and sched rework. If you could open separate issues of the failing cases it would help. Otherwise, I think it is just a bunch of new code that we need to stabilize.

**Comment by inducer** [comment]
OK, splitting this into individual  issues: #370 #371 #372.

I'm not having much luck bisecting even with just the major merge points. See #370.

**Comment by inducer** [comment]
Closing here.
