### ISSUE TITLE
Link failure with Clang 10.0.0 due to "undefined reference to 'getPollyPluginInfo()'"

### ISSUE THREAD

**Issue by Flamefire** [pocl/pocl#865]
When Clang/LLVM is build with Polly enabled the 10.0.0 versions seems to require explicitly linking against libpolly.a (and maybe others) or linking fails with `undefined reference to 'getPollyPluginInfo()'`

The full issue description is here: https://bugs.llvm.org/show_bug.cgi?id=44870

Apparently the problem should not occur if `find_package` is used to find llvm/clang: https://bugs.llvm.org/show_bug.cgi?id=44870#c29. However here a manual list of clang libs seem to be used: https://github.com/pocl/pocl/blob/dca3eb27ca210d92bb8d30370d7c643d26175906/cmake/LLVM.cmake#L230-L239

The issue is solved in 10.0.1 but it might be worth using the `find_package` integration instead to avoid similar problems in the future

**Comment by pjaaskel** [comment]
Since fixed in LLVM release branch, not urgent for 1.6.
